version: '2'
services:
   mariadb_1:
    image: mariadb:10.0.38
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: campaignmanager_db_1
      MYSQL_USER: suser@%
      MYSQL_PASSWORD: password
   mariadb_2:
    image: mariadb:10.0.38
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: campaignmanager_db_2
      MYSQL_USER: suser@%
      MYSQL_PASSWORD: password
   campaignmanager:
    container_name: campaign-manager
    build: .
    ports:
    - "8080:8080"
    - "8081:8081"
    volumes:
    - /var/log/campaign-manager
    environment:
      LOG_LEVEL: DEBUG
      SHARD0_CONNECTION_STRING: jdbc:mariadb://mariadb_1/campaignmanager_db_1?createDatabaseIfNotExist=true
      SHARD1_CONNECTION_STRING: jdbc:mariadb://mariadb_2/campaignmanager_db_2?createDatabaseIfNotExist=true
      DB_USER: root
      DB_PASSWORD: password
      SHARDS: 2
      OKTA_BASE_URL: ${OKTA_BASE_URL}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      KALEYRA_SMS_KEY: ${KALEYRA_SMS_KEY}
      KALEYRA_SMS_SENDERS: ${KALEYRA_SMS_SENDERS}
      KALEYRA_IVR_KEY: ${KALEYRA_IVR_KEY}
    depends_on:
      - mariadb_1
      - mariadb_2
